.vscode/launch.json
data_prep/postgresdb_lib.py

fix: add missing migration

---

.github/workflows/pr-open.yml

ci: catch canceled jobs

---

.github/workflows/pr-open.yml

ci(fix): catch canceled jobs

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml

chore(ci): actions moved to bcgov org

---

.github/workflows/.deploy.yml
.github/workflows/job-sync.yml
.github/workflows/merge.yml

chore(ci): use GH runner ubuntu-24.04

---

.github/workflows/.deploy.yml
.github/workflows/job-sync.yml
.github/workflows/pr-open.yml
sync/oc_run.sh
sync/openshift.deploy.yml

chore(ci): workflow and etl setup

---

.github/workflows/.deploy.yml
sync/openshift.deploy.yml

chore(ci): drop resource limits

---

.github/workflows/.deploy.yml

chore(ci): simplify deployer

---

.github/workflows/.deploy.yml
.github/workflows/pr-open.yml
sync/openshift.deploy.yml

chore(ci): run ETL in TEST_MODE=true after deployments

---

.github/workflows/.deploy.yml
.github/workflows/etl-prod.yml
.github/workflows/etl-test.yml
.github/workflows/job-sync.yml

chore(ci): TEST and PROD ETL jobs (test mode)

---

.github/workflows/.deploy.yml
.github/workflows/etl-prod.yml
.github/workflows/etl-test.yml
sync/junk.out

chore(ci): fix cronjob name in runner param

---

.github/workflows/.deploy.yml
.github/workflows/etl-prod.yml
.github/workflows/etl-test.yml

chore(ci): view cronjob logs

---

.github/workflows/.deploy.yml
.github/workflows/etl-prod.yml
.github/workflows/etl-test.yml

feat: tail cronjobs

---

.github/workflows/.deploy.yml
.github/workflows/etl-prod.yml
.github/workflows/merge.yml
sync/openshift.deploy.yml
sync/src/main.py

chore(ci): TEST_MODE=false for TEST env

---

.github/workflows/.deploy.yml
sync/junk.out

chore(ci): update envar, trigger deploy

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml

Workflow cleanup:
- database name
- timeout on init deploy
---

chore(ci): cleanup

---

sync/openshift.deploy.yml

chore(ci): fix pw envar

---

data_prep/db_env_utils/fix_forest_client_fk_violation.py

fix: tweaks to script to id fk constraint violations

---

.github/workflows/etl-prod.yml
.github/workflows/etl-test.yml

Kick off jobs using `sync/oc_run.sh`, which shows progress.
---

chore(ci): use script to follow cronjob

---

sync/src/main.py

fix: try to address ssl errors

---

.github/workflows/etl-prod.yml
.github/workflows/etl-test.yml

feat: add teams notifications

---

.github/workflows/.deploy.yml
.github/workflows/pr-open.yml
common/openshift.init.yml
sync/openshift.deploy.yml

see: https://github.com/bcgov/nr-fds-pyetl/issues/110
---

feat: 110 cleanup deploy

---

sync/src/module/data_synchronization.py

feat: 2089 when the SEEDLOT.ORIGINAL_SEED_QTY > 0, lock ownership
